name: bi_pati
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl:
  image_picker:
  path_provider:
  shared_preferences:
  http:
  font_awesome_flutter: ^9.1.0
  carousel_slider: ^1.3.1
  flutter_icons: ^1.1.0
  image_cropper:
  multi_select_flutter: ^4.0.0
  get:
  circular_countdown_timer: ^0.0.8
  flutter_swiper: ^1.1.6
  sliding_up_panel: ^1.0.0
  logger: ^1.0.0
  flutter_svg: ^0.22.0
  smooth_page_indicator: ^0.2.3
  animations: ^2.0.1
  flutter_map:
  geocoder:
  location:
  firebase_messaging: ^10.0.7
  searchable_dropdown: ^1.1.3
  google_maps_flutter: ^2.0.9
  flutter_ringtone_player: ^3.0.0
  google_mobile_ads: ^0.13.5
  qr_flutter:
  flutter_datetime_picker: ^1.5.1
  qr_code_scanner: ^0.6.1



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/
    - assets/animals/
    - assets/svg/
    - assets/icon/


  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf